index:
    path: /
    controller: App\Controller\MavenLinkController::index

maven_all_workspaces:
    path: /maven-all-workspaces
    controller: App\Controller\MavenLinkController::listAllProjects

jira_all_projects:
    path: /jira-all-projects
    controller: App\Controller\JiraApiController::getProjects
